# Generated by Django 4.1 on 2022-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=122)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("message", models.TextField()),
            ],
        ),
    ]
